nmap <C-j> <Plug>(edgemotion-j)
nmap <C-K> <Plug>(edgemotion-k)
omap <C-j> <Plug>(edgemotion-j)
omap <C-K> <Plug>(edgemotion-k)
smap <C-j> <Plug>(edgemotion-j)
smap <C-K> <Plug>(edgemotion-k)
xmap <C-j> <Plug>(edgemotion-j)
xmap <C-K> <Plug>(edgemotion-k)
