nmap <Leader>rc <Plug>(vim-fzy-rails_controllers)
nmap <Leader>rm <Plug>(vim-fzy-rails_models)
nmap <Leader>rv <Plug>(vim-fzy-rails_views)
nmap <Leader>rd <Plug>(vim-fzy-rails_decorators)
nmap <Leader>rp <Plug>(vim-fzy-rails_packs)
nmap <Leader>rj <Plug>(vim-fzy-rails_javascripts)
nmap <Leader>rsa <Plug>(vim-fzy-rails_stylesheets)
nmap <Leader>rse <Plug>(vim-fzy-rails_serializers)
