Abbr i tihs this
Abbr i adn and
Abbr i REact React
Abbr i ): );
Abbr i initalize initialize
Abbr c fzf FZF
Abbr c cdu Cdu
Abbr c unite Unite
Abbr c tig Tig
Abbr c ggrep Ggrep
Abbr c gdiff Gdiff
Abbr c hgrep Hgrep
Abbr c gist Gist
Abbr c GGrep Ggrep
